language: go
sudo: false
go:
  - 1.12.x

env:
  global:
  - GO111MODULE=on
  - GO_FOR_RELEASE=1.12.x
  - IMAGE_NAME=sealtv/identidock

git:
  depth: 1

  install: true

notifications:
  email: true

before_script:
  - go get -v
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0
  - golangci-lint --version

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled
  - ./sm-push.sh